#!/usr/bin/env python3
"""Vendor the Google Fonts used by the site into public/fonts/.

fonts.googleapis.com is a blackhole from mainland China. A render-blocking
stylesheet pointing there means the browser paints nothing until the request
times out, so visitors get a blank page rather than a slow one.

Only the `latin` subset is kept: these families carry no CJK glyphs, so Chinese
text falls back to system fonts either way.

Output: public/fonts/*.woff2 + src/styles/fonts.css
Run: npm run fonts:vendor
"""

from __future__ import annotations

import hashlib
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "public" / "fonts"
CSS_OUT = ROOT / "src" / "styles" / "fonts.css"

CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Barlow+Condensed:wght@500;600;700"
    "&family=Bodoni+Moda:opsz,wght@6..96,400;6..96,500;6..96,600"
    "&family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400;1,500"
    "&family=Figtree:wght@300;400;500;600"
    "&family=Work+Sans:wght@400;500;600"
    "&display=swap"
)

# Google serves woff2 only to browsers that advertise support.
UA = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"
    )
}

HEADER = """/*
 * Self-hosted webfonts — generated by scripts/vendor-google-fonts.py.
 * Do not edit by hand; re-run `npm run fonts:vendor` instead.
 *
 * These must never be fetched from fonts.googleapis.com: that host is
 * unreachable from mainland China, and a render-blocking stylesheet pointing
 * at it leaves visitors staring at a blank page until the request times out.
 */
"""


def fetch(url: str) -> bytes:
    return urllib.request.urlopen(urllib.request.Request(url, headers=UA)).read()


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    css = fetch(CSS_URL).decode("utf-8")

    # Each @font-face is preceded by a /* subset */ marker comment.
    blocks = re.findall(r"/\* ([a-z-]+) \*/\s*(@font-face \{.*?\})", css, re.S)
    if not blocks:
        raise SystemExit("Could not parse any @font-face blocks from Google's CSS")

    for stale in OUT_DIR.glob("*.woff2"):
        stale.unlink()

    kept: list[str] = []
    # Variable families come back as the same file for every requested weight,
    # so dedupe on content and let several @font-face rules share one download.
    by_digest: dict[str, str] = {}
    for subset, block in blocks:
        if subset != "latin":
            continue

        url = re.search(r"src: url\((https://[^)]+\.woff2)\)", block).group(1)
        family = re.search(r"font-family: '([^']+)'", block).group(1)
        weight = re.search(r"font-weight: ([\d ]+);", block).group(1).strip()
        style = re.search(r"font-style: (\w+);", block).group(1)

        data = fetch(url)
        digest = hashlib.sha256(data).hexdigest()
        name = by_digest.get(digest)
        if name is None:
            slug = family.lower().replace(" ", "-")
            name = f"{slug}-{weight.replace(' ', '-')}-{style}.woff2"
            (OUT_DIR / name).write_bytes(data)
            by_digest[digest] = name

        local = block.replace(f"url({url})", f"url('/fonts/{name}')")
        if "font-display" not in local:
            local = local.replace("@font-face {", "@font-face {\n  font-display: swap;")
        kept.append(local)

    total = sum(f.stat().st_size for f in OUT_DIR.glob("*.woff2"))

    CSS_OUT.write_text(HEADER + "\n".join(kept) + "\n", encoding="utf-8")

    families = sorted({re.search(r"font-family: '([^']+)'", b).group(1) for b in kept})
    print(f"{len(kept)} @font-face rules → {len(by_digest)} files, {total / 1024:.0f} KB total")
    print("families:", ", ".join(families))
    print(f"wrote {CSS_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
